### PR TITLE
Enhancement: Profile Interface with Save Functionality

### PR DESCRIPTION
**Pull request by genesist45**
This PR enhances the profile interface, allowing users to view and update their Name and Email with the ability to save changes.

Changes:

Improved UI for the profile page.
Added editable fields for Name and Email.
Integrated a Save button to store updates.
Included form validation and API integration for saving changes.

### CODE REVIEW

**Review by feranilgerby — APPROVED** [review]

**Review by kjdinlay — APPROVED** [review]
👌🏻

**Review by Plongix — APPROVED** [review]
Nice

**Comment by justinolavides** [comment]
good

**Review by Ian5601 — APPROVED** [review]
🫡

**Review by Elliad007 — APPROVED** [review]
Nice

**Review by justinolavides — APPROVED** [review]

**Pull request merged**
