### PR TITLE
Header with Title, Contact UI, and About Us UI

### PR DESCRIPTION
**Pull request by justinolavides**
This PR introduces a header with a title, along with UI components for the contact and about us sections. The header structure and layout are complete, while the contact and about us interfaces are still under development.
Features created/files changed:

Implemented header with a title section.
Added UI components for the contact and about us sections.
Basic layout and styling of the header are complete.
Contact and about us UI are in progress.

### CODE REVIEW

**Review by genesist45 — APPROVED** [review]
nc

**Review by Plongix — APPROVED** [review]
Nc G

**Review by kjdinlay — APPROVED** [review]
👌🏻

**Comment by ajabao28** [comment]
O

**Comment by feranilgerby** [comment]
Wow

**Comment by Ian5601** [comment]
🤞🏼

**Comment by feranilgerby** [comment]
Nc 1

**Comment by ajabao28** [comment]
J

**Pull request merged**
