### PR TITLE
Profile Page Creation (In Progress)

### PR DESCRIPTION
**Pull request by genesist45**
This PR is focused on the ongoing development of the profile page, which allows users to view and manage their personal information. The page layout and basic structure have been set up, with further functionality (editing and updating profile details) still in progress.
Features created/files changed:

Created the basic structure for the Profile Page.
Designed components for displaying user information (e.g., name, email).
Applied initial styling and layout.
Profile editing functionality is still under development.

### CODE REVIEW

**Comment by Ian5601** [comment]
❤️

**Review by justinolavides — APPROVED** [review]
goods

**Review by Ian5601 — APPROVED** [review]
Nice

**Review by feranilgerby — APPROVED** [review]

**Review by Plongix — APPROVED** [review]
Nice

**Review by Elliad007 — APPROVED** [review]
♥️

**Comment by ajabao28** [comment]
H

**Review by ajabao28 — COMMENTED** [review]
H

**Pull request merged**
