### PR TITLE
Enhancement: Playlist Page with Temporary Music Samples

### PR DESCRIPTION
**Pull request by genesist45**
This PR enhances the playlist page, allowing users to create playlists using temporary music samples.

Changes:
Added functionality to create playlists.
Displayed temporary music samples for playlist creation.
Simplified UI to focus on creating and organizing playlists.
No API integration for permanent data storage at this stage.

### CODE REVIEW

**Review by Ian5601 — APPROVED** [review]
🫡

**Review by Plongix — APPROVED** [review]
Goods

**Review by justinolavides — APPROVED** [review]
goods

**Review by Elliad007 — APPROVED** [review]

**Review by kjdinlay — APPROVED** [review]
👌🏻

**Review by feranilgerby — APPROVED** [review]

**Pull request merged**
