### PR TITLE
Merge pull request #3 from justinolavides/justin

### PR DESCRIPTION
**Pull request by justinolavides**
LOGIN-APP

### CODE REVIEW

**Comment by justinolavides** [comment]
login function

**Comment by genesist45** [comment]
Task 1: Login UI (mockup interface in React)
https://trello.com/c/c5mvF00R/15-task-1-login-ui-mockup-interface-in-react

**Comment by genesist45** [comment]
Task 2: Create Login API (coded in Laravel)
https://trello.com/c/QXQSpYRy/46-task-2-create-login-api-coded-in-laravel

**Comment by genesist45** [comment]
Task 3: Login Integration (connect API with UI)
https://trello.com/c/QhfpMnct/47-task-3-login-integration-connect-api-with-ui

**Comment by genesist45** [comment]
Task 4: User Registration UI (mockup interface in React)
https://trello.com/c/2rvgGD04/116-task-4-user-registration-ui-mockup-interface-in-react

**Comment by genesist45** [comment]
Task 5: User Registration API (coded in Laravel)
https://trello.com/c/W3G3c1e6/117-task-5-user-registration-api-coded-in-laravel

**Comment by genesist45** [comment]
Task 6: User Registration Integration (connect API with UI)
https://trello.com/c/JNGmaflh/118-task-6-user-registration-integration-connect-api-with-ui

**Pull request merged**
