### PR TITLE
Settings UI: Profile Management, Password Change, Notifications, Theme Customization, and Logout

### PR DESCRIPTION
**Pull request by genesist45**
This PR enhances the settings UI by adding features for profile management, password change, and theme customization. It includes components for user profile management, notification preferences, and logout functionality. The password change and notification features are in progress and still being fixed.
Features created/files changed:

Added Profile component to manage user details.
Integrated ThemeSelector for theme customization.
Implemented Logout functionality for user session management.
Started implementing ChangePassword and Notification components (still under development).

### CODE REVIEW

**Review by Ian5601 — APPROVED** [review]
❤️

**Review by Plongix — APPROVED** [review]
Goods

**Review by justinolavides — APPROVED** [review]
Ohyieahh

**Review by kjdinlay — APPROVED** [review]
👌🏻

**Review by feranilgerby — APPROVED** [review]

**Review by feranilgerby — APPROVED** [review]

**Review by ajabao28 — COMMENTED** [review]
H

**Pull request closed without merging**
